<div class="blog">
    <h1 class="blog_title">JEROME DREYFUSS TAKES ON <br/>ROUTE 66: PART TROIS</h1>
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/blog2/blog1.jpg" width="100%" />
    <p class="blog_line"></p>
    <p class="blog_content">content.This is the content.This       is the content.This is the contentThis is the content.This is the content..This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.</p>
    <p class="blog_content">This is the content This is the content.This is the content This is the content.</p>
    <p class="blog_content">content.This is the content.Thisis the contentThis is thesss ffff contentThis is the content.This is the contentThis is the content.This is the contentThis is the content.This is the content.This is the contentThis is the content.This is the content.This is the contentsssssssshis is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.</p>
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/blog2/blog2.jpg" width="100%" />
    <p class="blog_content">content.This is the content.Thisis the contentThis is thesss ffff contentThis is the content.This is the contentThis is the content.This is the contentThis is the content.This is the content.This is the contentThis is the content.This is the content.This is the contentsssssssshis is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.</p>
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/blog2/blog3.jpg" width="100%" />
    <p class="blog_content">This is the content This is the content.This is the content This is the content.</p>
    <p class="blog_content">content.This is the content.Thisis the contentThis is thesss ffff contentThis is the content.This is the contentThis is the content.This is the contentThis is the content.This is the content.This is the contentThis is the content.This is the content.This is the contentsssssssshis is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.This is the content.</p>
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/blog2/blog4.jpg" width="100%" />
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/blog2/blog5.jpg" width="100%" />
    <p class="blog_content">content.This is the content.Thisis the contentThis is thesss ffff contentThis is </p>
</div>    

