<div class="homme">
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/chaussures/chaussures1.jpg" />
    <p class="title">BEA</p>
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/chaussures/chaussures2.jpg" />
    <p class="title">BIBOOTS</p>
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/chaussures/chaussures3.jpg" />
    <p class="title">BIBOOTS FRANGE</p>
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/chaussures/chaussures4.jpg" />
    <p class="title">FRANCOISE</p>
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/chaussures/chaussures5.jpg" />
    <p class="title">CHEYENNE</p>
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/chaussures/chaussures6.jpg" />
    <p class="title">PINPIN</p>
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/chaussures/chaussures7.jpg" /> 
    <p class="title">RUN</p> 
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/chaussures/chaussures8.jpg" /> 
    <p class="title">SUZANNE</p>  
    <img src="<?php echo Yii::app()->request->baseUrl; ?>/images/chaussures/chaussures9.jpg" /> 
    <p class="title">WANDA</p>   
</div>  
